### ----------------------------------------------------------------------
### Copyright (C) 2019 Geraldo Ribeiro <geraldo@intmain.io>
### ----------------------------------------------------------------------

USE_CATCH_TEST_SUITE=YES

include /opt/intmain/dev/$(OS)/usr/share/Gr/scripts/Common/Makefile.include

all: \
	TestSuiteCatch$(EXT)

clean: clean-test
	$(RM) TestSuiteCatch$(EXT)
	$(RM) *.o *.gcda *.gcno
	$(RM) output/*.txt
