### ----------------------------------------------------------------------
### Copyright (C) 2019 Geraldo Ribeiro <geraldo@intmain.io>
### ----------------------------------------------------------------------

GR_DEBIAN_PACKAGE_BASENAME=intmain-grbenchmark-dev
GR_DEBIAN_PACKAGE_CUSTOMER_APP_ID=
GR_DEBIAN_PACKAGE_DESCRIPTION=Medidor de tempo de execução

NOMEDOPROJETO=GrBenchmark
VERSAODOPROJETO=0.1.0
OUTROSFONTESDOPROJETO=""

include /opt/intmain/dev/$(OS)/usr/share/Gr/scripts/Common/Makefile.include

all:
	echo "OK"

clean:
	echo "OK"

